# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classification.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1084, 651)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.upload = QtWidgets.QPushButton(Form)
        self.upload.setGeometry(QtCore.QRect(60, 500, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.upload.setFont(font)
        self.upload.setObjectName("upload")
        self.interference = QtWidgets.QPushButton(Form)
        self.interference.setGeometry(QtCore.QRect(500, 500, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.interference.setFont(font)
        self.interference.setObjectName("interference")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(480, 130, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(480, 260, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.xrayback = QtWidgets.QPushButton(Form)
        self.xrayback.setGeometry(QtCore.QRect(1000, 0, 81, 31))
        self.xrayback.setObjectName("xrayback")
        self.imglabel = QtWidgets.QLabel(Form)
        self.imglabel.setGeometry(QtCore.QRect(70, 80, 351, 331))
        self.imglabel.setMinimumSize(QtCore.QSize(224, 224))
        self.imglabel.setText("")
        self.imglabel.setObjectName("imglabel")
        self.result = QtWidgets.QLabel(Form)
        self.result.setGeometry(QtCore.QRect(690, 120, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setScaledContents(True)
        self.result.setObjectName("result")
        self.score = QtWidgets.QLabel(Form)
        self.score.setGeometry(QtCore.QRect(650, 260, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.score.setFont(font)
        self.score.setText("")
        self.score.setScaledContents(True)
        self.score.setObjectName("score")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.upload.setText(_translate("Form", "上传图片"))
        self.interference.setText(_translate("Form", "开始推理"))
        self.label.setText(_translate("Form", "检测结果"))
        self.label_2.setText(_translate("Form", "置信度"))
        self.xrayback.setText(_translate("Form", "返回"))
